version: '3.7'

services:

  hub:
    image: selenium/hub:3.141.59
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome-debug:latest
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    ports:
      - 5905:5900
    expose:
      - "5900"
    volumes:
    - /dev/shm:/dev/shm

  firefox:
    image: selenium/node-firefox-debug:latest
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    ports:
      - 5906:5900
    expose:
      - "5900"
    volumes:
      - /dev/shm:/dev/shm